### ISSUE TITLE
TL6 Geiger Counter is missing from the High Tech Equipment list

### ISSUE THREAD

**Issue by tjed** [richardwilkes/gcs_master_library#109]
TL6 Geiger Counter is missing from the High Tech equipment list (the TL8 is listed, though) 

This was listed on page 49 of the GURPS High Tech book

Bizarrely, the After the End equipment list does have the TL6 Geiger Counter (with a cost modifier)

**Comment by richardwilkes** [comment]
I've transferred this issue and previous ones to the gcs_master_library repo. Please make sure you post into the correct repo in the future.

**Comment by Calmquist** [comment]
I fixed this in #136.
