### ISSUE TITLE
Create Dwarven ancestry data

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs_master_library#112]
As of GCS v4.35, it has been possible to create custom ancestry data to control how the various randomizable attributes on a character sheet are generated.

**Comment by Calmquist** [comment]
I currently have a dwarven ancestry data with adjusted height and weight and lists of "dwarf sounding" names. I can have a PR out fairly soon.

**Comment by Calmquist** [comment]
I created an initial PR #137 for this.

**Comment by Calmquist** [comment]
The names list still needs improvement.
