### ISSUE TITLE
Create Elven ancestry data

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs_master_library#113]
As of GCS v4.35, it has been possible to create custom ancestry data to control how the various randomizable attributes on a character sheet are generated.

**Comment by Calmquist** [comment]
This one seems like it could be more involved than the other two. Generic fantasy elves and Dungeon Fantasy elves often have similar physical description, but the DF elves have colorful hair. A standard naming scheme for the ancestry files may be helpful.

**Comment by richardwilkes** [comment]
Added in 6d69d9a128d493680a4cc32c1a842222ff4a2c5d
