### ISSUE TITLE
[Master Library] Added conditional modifiers to Hard to Kill and Hard to Subdue

### ISSUE THREAD

**Issue by Grayscalae** [richardwilkes/gcs_master_library#120]
Added conditional modifiers to:

Hard to Kill: on all HT rolls to avoid death at -1xHP or below and any HT roll that would result in instant death

Hard to Subdue: on all HT rolls to avoid uncounsciousness
[Basic Set Advantages.zip](https://github.com/richardwilkes/gcs_master_library/files/7797819/Basic.Set.Advantages.zip)

**Comment by richardwilkes** [comment]
I didn't take this change directly, but instead went through the Basic Set Advantages and made conditional modifiers out of things that were previously in notes. See commit 845af4af6893a4e4a0cd128ab5cb082802240171

**Comment by Grayscalae** [comment]
Looks even better.
