### ISSUE TITLE
Add Crewman skill to Basic Set skill list

### ISSUE THREAD

**Issue by Patchcoat** [richardwilkes/gcs_master_library#122]

**Comment by Calmquist** [comment]
Crewman is in the skill list as the individual named specialties: Airshipman, Seamanship, Spacer and Submariner. It is a skill that requires specialization. Do you want something like Crewman (<Configurable Specialty>)?

**Comment by richardwilkes** [comment]
That depends on whether there are any references to it for defaults. Whatever those are is what should be provided.

**Comment by Calmquist** [comment]
At least in the Basic Set, no skill defaults to Crewman. I am not sure any skill could default to Crewman by RAW since "there is a separate skill for each class of vessel." There are defaults to Airshipman, Seamanship, Spacer and Submariner.

**Comment by richardwilkes** [comment]
That's what I assume and would be why there are no listings like "Crewman (Airshipman)".

**Comment by Calmquist** [comment]
In that case, I am not sure there is anything to do for this issue. I don't think Crewman should be added since it already exists as its specializations. Perhaps Crewman could be added as a category for the specializations, but I don't think it should be added as a skill.

**Comment by richardwilkes** [comment]
I tend to agree. Just haven't had the opportunity lately to really take a look. Given what you've looked at and communicated, I'm going to close this out without any changes to the library. @Patchcoat if you'd like to make an argument in favor of actually making a change for this, please feel free to re-open and make your case.
