### ISSUE TITLE
Output Template Loop Counter Documentation 

### ISSUE THREAD

**Issue by cyberianfrontier** [richardwilkes/gcs_master_library#125]
Documentation on the Loop Counters is missing from the Output Template Documentation at https://gurpscharactersheet.com/output_templates.html

The new Output Template variables are available for loops.  The new variables follow the same format as the loop start variable — replace “_START” with “_COUNT”. 

 IE @RANGED_LOOP_COUNT

**Comment by richardwilkes** [comment]
Added and pushed to the web site
