### ISSUE TITLE
Martial Arts Iron Legs incorrect location DR

### ISSUE THREAD

**Issue by ScarletDolly** [richardwilkes/gcs_master_library#140]
The Iron Legs advantage/perk is supposed to grant additional DR to the legs only if additional points are spent, with a single point obtaining bonus effect ST to the area to make it safer to kick and the like. However, as it is currently coded, it instead functions exactly like Iron Hands, granting Hand DR at 1 point per rank.
![image](https://user-images.githubusercontent.com/103339545/162607398-09f7ff0c-d4fe-46fb-8eee-31f5fbf0d8f6.png)

**Comment by richardwilkes** [comment]
Fixed as part of b822a2d749a74768576f4c658b9c685ce9f856e1
