### ISSUE TITLE
Can't add limited use limitation modifier to Spells

### ISSUE THREAD

**Issue by purplemango90** [richardwilkes/gcs_master_library#169]
As the title says, limited use modifiers cannot be added to spells or skills, only to advantages and disadvantages for some reason.

**Comment by richardwilkes** [comment]
This has never been supported, as I'm unaware of any cases where it is necessary in the rules. Do you have an example where this might be useful?

**Comment by purplemango90** [comment]
I'm sorry, I am new to GURPS and realized I misunderstood the rule.

I wanted to add it to a spell to cheapen the cost per level, but realized it can only be used on spells when using the magic as powers(advantages) system.

**Comment by richardwilkes** [comment]
No worries. I'm going to close this.
