### ISSUE TITLE
v5.0.0 installer does not open

### ISSUE THREAD

**Issue by vensha01** [richardwilkes/gcs_master_library#173]
I tried to download GCS v5.0.0 today for Windows 10 but after extracting and running the file as administrator it won't open. I checked the FAQ and looked for a "%SystemRoot%\Sun\Java\lib\ext" folder to delete, but I have no folder, so I don't think it's a problem with Java. Several installations won't work. My installation of GCS 4.37.1 works fine. I'm wondering if anyone else has had this issue.

**Comment by richardwilkes** [comment]
v5 and later are no longer written in Java. The issue you ran into was due to a bug that causes a crash during startup if certain types of old settings data are present. I've released a v5.0.1 to (hopefully) address this.

**Comment by vensha01** [comment]
Just installed v5.0.1 and it works. My man,
