### ISSUE TITLE
Referenced PDF aren't opening on GCS

### ISSUE THREAD

**Issue by guijsouza** [richardwilkes/gcs_master_library#19]
Previously, referenced books were open inside GCS in a tab, with the term highlighted. Now, when I click "open reference page", my web browser opens with the pdf file.
Is this a new feature or a bug?

**Comment by richardwilkes** [comment]
This is working as intended. The internal PDF renderer was causing maintenance issues and had some bad behavior that couldn’t be easily fixed. The new method also has some problems (a lack of ability to ask it to highlight the term automatically is one), but overall is more maintainable and more importantly, is better supported.

There is also a PR in progress to add the ability to launch a third-party PDF viewer of your choice. The downside of that approach — and why I had not used it previously — is that the vast majority of PDF viewers will not respond correctly to requests to open to specific pages, or will only work for the first attempt. There’s also the issue of cross-platform support and no PDF viewer I’ve found actually works at all on all three platforms I require.

**Comment by guijsouza** [comment]
😭😭😭😭

**Comment by guijsouza** [comment]
Thanks for the reply. Beside this, your software is awesome. Save a lot of time.

Thanks!!
