### ISSUE TITLE
Striker Advantages Missing Modifiers

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs_master_library#205]
I'm not sure whether it is intentional, or if there's some limitation with implementation, but all Strikers are missing modifiers completely, but I've seen it be a problem for a long time. You have to edit them manually each time to add the modifiers. So, it would be nice if they were there even if they didn't do anything, so they can be enabled to make modifications to their cost.

**Comment by richardwilkes** [comment]
I generally don't create any of the data files myself and leave that to the community to provide. So... if you're interested in this, the best thing to do would be to make the suggested modifications and submit them as a Pull Request.

**Comment by Legendsmith** [comment]
I'll get onto this. I keep noticing it and forgetting about it. It's been literally years of me going "I need to add striker modifiers."
