### ISSUE TITLE
update advantage Gunslinger

### ISSUE THREAD

**Issue by tuomaslorenzo** [richardwilkes/gcs_master_library#242]
[gunslinger_updated.json](https://github.com/richardwilkes/gcs_master_library/files/12872561/gunslinger_updated.json)
add bonuses to techniques defaults: fast-firing, fanning, quik-shot, thumbing and two-handed thumbing in new file. Ref: Gunfu pg15

**Comment by rinickolous** [comment]
Thanks for the update. Implemented via #256
