### ISSUE TITLE
Wrong book abbreviation for Transhuman Space

### ISSUE THREAD

**Issue by NilsRichter** [richardwilkes/gcs_master_library#247]
Hi,

this is my first reported bug, so please be gentle with me but feel free to let me now, if I should do something differently next time.

I noticed that in the Master Library (v4.16) several traits (e.g. all Infromorph templates) the page references use the abbreviation TS (Tactical Shooting), not THS, which it should be according to https://gurpscharactersheet.com/page_references.html

I would guess that a replace in the "reference" tags (TS->THS) should fix the problem ("TS" is not part of any other relevant references).

On a personal note: I've played GURPS since the 90s and always used the GCA, which seems to be defunct now. So I was very happy to find the GCS project after a hiatus. Thank you for the great work. I might try to help fill the Master Library out (maybe with more Transhuman Space stuff) if a get some free time.

Cheers,
    Nils.

**Comment by richardwilkes** [comment]
Thanks for reporting the issue. The best way to get it fixed is to create a Pull Request (PR) in this repo with the needed changes. The vast majority of the data files have been contributed by folks like you.
