### ISSUE TITLE
Small fix or addition - Skill Interface

### ISSUE THREAD

**Issue by TheRockThatRolls** [richardwilkes/gcs_master_library#291]
In the relative skill level (RSL) column, when putting a technique's default to dodge it doesn't show up in it (the RSL just shows "+0" and not "Dodge +0"). Perhaps it is meant to be for lack of space or just an overlook, but thought I'd mention it.

**Comment by richardwilkes** [comment]
All techniques only show a number under RSL, since it is always relative to the skill they are a technique for.
