### ISSUE TITLE
Create option to add follow-up damage in same weapon usage

### ISSUE THREAD

**Issue by SavageGM** [richardwilkes/gcs_master_library#297]
I want to be able to have this damage ``6dx14(2) pi++ with a follow-up 3d-1 [2d+2] cr ex`` in one weapon attack entry. Currently it can only be done with a separate entry.
see below.
![image](https://github.com/richardwilkes/gcs_master_library/assets/148233089/228da336-60b6-4311-be93-558ddc92c655)

**Comment by richardwilkes** [comment]
You can add arbitrary text in the `Type` field if you want it to show up at the end of the Damage entry. You won't get any calculations automated for you that way, but it works if you want them put together.
