### ISSUE TITLE
FoundryVTT: Import Equipment Library error.

### ISSUE THREAD

**Issue by slaapliedje** [richardwilkes/gcs_master_library#310]
I have attempted to import the DFRPG Equipment library into FoundryVTT, but get an error of "Invalid Compendium Pack Data: name: Package and compendium pack IDs may only be alphanumeric with hypens or underscores."

Renaming the file to not have spaces in it (in this example, I renamed the file to DFRPG_Equipment.eqp) and then FoundryVTT would allow it to be imported.

**Comment by richardwilkes** [comment]
The guys that work on the Foundry GURPS Game Aid generally don't look at the GCS issues lists (for the app or the data files). I'd recommend filing it against their project instead.

**Comment by slaapliedje** [comment]
Thanks.
It looks like someone beat me to it.  https://github.com/crnormand/gurps/issues/1926
