### ISSUE TITLE
Can't use body type or attribute presets anymore

### ISSUE THREAD

**Issue by Deliphin** [richardwilkes/gcs_master_library#87]
This is a regression. I saw the option a few versions back, and just noticed it's gone. I can still manually edit the attributes and body type, but there's no way to load presets anymore.

Arch Linux (amd64, linux 5.13.8-arch1-1)
GCS 4.34 (Java 15.0.2)

Windows 10 (amd64, version 21H1, build 19043.1110)
GCS 4.34 (Java 15.0.2)

I'm making this an issue as I don't see any other issues or open/closed pull requests explaining why it's been removed, so I'm assuming it's a bug.

**Comment by richardwilkes** [comment]
No, not a regression. It's in the menus: Settings > Body Type... and Settings > Default Body Type...

There is a control in the toolbar in those windows to pull up different pre-defined body types, but this also allows you to fully customize them, unlike before.
